package edu.spring.movielike.controller;

import java.util.Arrays;
import java.util.List;

public class MovieDataProvider {
	
	String[] genreArray = {
		"Action",
		"Adventure",
		"Animation",
		"Biography",
		"Comedy",
		"Crime",
		"Documentary",
		"Drama",
		"Erotic",
		"Family",
		"Fantasy",
		"Historical",
		"Horror",
		"Musical",
		"Mystery",
		"Political",
		"Romance",
		"SF",
		"Sport",
		"Thriller",
		"War",
		"Western"
	};
	
	String[] countryArray = {
			"Afghanistan",
			"Albania",
			"Algeria",
			"Argentina",
			"Armenia",
			"Australia",
			"Austria",
			"Azerbaijan",
			"Belarus",
			"Belgium",
			"Bolivia",
			"Bosnia and Herzegowina",
			"Botswana",
			"Brazil",
			"Bulgaria",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Chile",
			"China",
			"Colombia",
			"Congo",
			"Costa Rica",
			"Croatia",
			"Cuba",
			"Cyprus",
			"Czech Republic",
			"Denmark",
			"Dominican Republic",
			"Ecuador",
			"Egypt",
			"Estonia",
			"Finland",
			"France",
			"Georgia",
			"Germany",
			"Greece",
			"Haiti",
			"Honduras",
			"Hong Kong",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran",
			"Iraq",
			"Ireland",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Kazakhstan",
			"Kenya",
			"South Korea",
			"North Korea",
			"Kuwait",
			"Kyrgyzstan",
			"Latvia",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macedonia",
			"Madagascar",
			"Malaysia",
			"Malta",
			"Mexico",
			"Monaco",
			"Mongolia",
			"Morocco",
			"Mozambique",
			"Namibia",
			"Nepal",
			"Netherlands",
			"New Zealand",
			"Nicaragua",
			"Norway",
			"Pakistan",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Puerto Rico",
			"Qatar",
			"Romania",
			"Russia",
			"San Marino",
			"Saudi Arabia",
			"Senegal",
			"Singapore",
			"Slovakia",
			"Slovenia",
			"South Africa",
			"Spain",
			"Sri Lanka",
			"Sweden",
			"Switzerland",
			"Taiwan",
			"Thailand",
			"Tunisia",
			"Turkey",
			"Ukraine",
			"United Arab Emirates",
			"United Kingdom",
			"USA",
			"Uruguay",
			"Uzbekistan",
			"Venezuela",
			"Vietnam",
			"Yugoslavia"
	};

	public List<String> getGenreList() {
		List<String> genreList = Arrays.asList(genreArray);
		return genreList;
	}

	public List<String> getCountryList() {
		List<String> countryList = Arrays.asList(countryArray);
		return countryList;
	}

}
